[metadata]
name = jacobtools
version = 0.0.3
url = 'https://github.com/AbisheakJacob/jacobtools'
author = Abisheak Jacob J 
author_email = "AbisheakJacob0032" abisheakjacob0032@gmail.com
description = This package contains functions that help me tackle my day to day data andalytics requirements
long_description = README.md 
long_description_content_type = text/markdown
license = MIT
license_file = LICENSE 
classifiers= 
  License :: OSI Approved :: MIT License 

[options]
package_dir =
  =src
packages = find:
include_package_data = True

[options.packages.find]
where = src
exclude = 
  test*
